### PR TITLE
Modify .stories files for CourseDetailsPage and CourseDetailsTable

### LINKED ISSUE #26: Priority: Modify .stories (storybook) File for CourseDetails
Relies on #18

### PR DESCRIPTION
**Pull request by ThatsBadJuju**
Closes #26 

In this PR, I modified the .stories files to match what the CourseDetailsPage does. I didn't need any modification for CourseDetailsTable, since that was already correct on the storybook. 

CourseDetailsPage should be mostly blank because it isn't linked to any course quarter/enrollCode itself.

Storybook screenshots:

CourseDetailsTable storybook:
image

CourseDetailsPage storybook:
image

In order to complete this PR, first complete PR #45 first, then merge into here to fix CourseDetailsPage and CourseDetailsTable tests.

### CODE REVIEW

**Review by pconrad — CHANGES_REQUESTED** [review]
Some commented out code, and some variables that are unused (and can probably be deleted)

**Review by pconrad — DISMISSED** [review]
LGTM

**Review by rosillo-m — DISMISSED** [review]
LGTM!

**Review by pconrad — DISMISSED** [review]
LGTM, but waiting on earlier PR

**Review by pconrad — APPROVED** [review]
LGTM!

**Review by rosillo-m — APPROVED** [review]
LGTM

**Pull request merged**
